export NCCL_P2P_DISABLE=1
output_model='/root/autodl-tmp/sft_ner'
deepspeed --num_gpus=1 run.py \
    --model_name_or_path  /root/qwen2 \
    --train_files /root/sft/data/train.csv \
    --validation_files /root/sft/data/test.csv \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train True \
    --do_eval True \
    --use_fast_tokenizer false \
    --output_dir ${output_model} \
    --evaluation_strategy  steps \
    --max_eval_samples 200 \
    --learning_rate 1e-4 \
    --gradient_accumulation_steps 2 \
    --num_train_epochs 1 \
    --warmup_steps 10 \
    --load_in_bits 4 \
    --lora_r 8 \
    --lora_alpha 32 \
    --target_modules q_proj,k_proj,v_proj,o_proj,down_proj,gate_proj,up_proj \
    --logging_dir ${output_model}/logs \
    --logging_strategy steps \
    --logging_steps 100 \
    --save_strategy epoch \
    --eval_steps 100 \
    --preprocessing_num_workers 1 \
    --save_total_limit 20 \
    --seed 42 \
    --disable_tqdm false \
    --ddp_find_unused_parameters false \
    --block_size 4096 \
    --report_to tensorboard \
    --overwrite_output_dir \
    --deepspeed ds_config_zero2.json \
    --ignore_data_skip true \
    --bf16 \
    --gradient_checkpointing \
    --bf16_full_eval \
    --ddp_timeout 18000000 \
    | tee -a ${output_model}/train.log